// Base de datos consolidada (tomada de completar.html)
const baseDatos = {
    residencial: [
        { n: "Limpieza y Descapote", u: "m2", c: 1.0, p: 15, m: "Herramienta menor", r: "25 m²/día" },
        { n: "Trazo y Niveles", u: "m2", c: 1.0, p: 18, m: "Cal, estacas, hilos", r: "45 m²/día" },
        { n: "Excavación Cimiento", u: "m3", c: 0.1, p: 95, m: "Manual (suelo semiduro)", r: "4 m³/día" },
        { n: "Cimiento Corrido (0.4x0.2m)", u: "ml", c: 1.0, p: 285, m: "Hierro 3/8, Cemento 3k PSI", r: "7 ml/día" },
        { n: "Levantado Sobrecimiento", u: "m2", c: 0.8, p: 145, m: "Block 14cm, mortero", r: "13 m²/día" },
        { n: "Solera Hidrófuga", u: "ml", c: 0.8, p: 130, m: "Aditivo imperm., conc.", r: "11 ml/día" },
        { n: "Drenajes PVC (4', 2')", u: "ml", c: 1.2, p: 115, m: "Tubería, accesorios, pegamento", r: "15 ml/día" },
        { n: "Relleno Compactado Selecto", u: "m3", c: 0.2, p: 220, m: "Material selecto, agua", r: "7 m³/día" },
        { n: "Contrapiso (e=0.07m)", u: "m2", c: 1.0, p: 98, m: "Concreto 2k PSI", r: "28 m²/día" },
        { n: "Levantado Muros Block (14cm)", u: "m2", c: 2.5, p: 155, m: "Block 14cm, mortero 1:4", r: "14 m²/día" },
        { n: "Columnas y Pines", u: "unid", c: 0.1, p: 450, m: "Acero 3/8, conc. 3k PSI", r: "3.5 unid/día" },
        { n: "Solera Intermedia", u: "ml", c: 1.5, p: 110, m: "Acero 3/8, conc. 3k PSI", r: "15 ml/día" },
        { n: "Solera de Corona", u: "ml", c: 1.0, p: 145, m: "Acero 3/8, conc. 3k PSI", r: "10 ml/día" },
        { n: "Sillares y Dinteles", u: "ml", c: 0.5, p: 120, m: "Acero, conc. para vanos", r: "6 ml/día" },
        { n: "Encofrado Losa (Obra Falsa)", u: "m2", c: 1.0, p: 65, m: "Madera, parales, desmoldante", r: "18 m²/día" },
        { n: "Ductería Eléctrica en Losa", u: "salida", c: 0.8, p: 260, m: "Poliducto, cajas, alambres", r: "9 sal/día" },
        { n: "Armado Losa (Vigueta/Bovedilla)", u: "m2", c: 1.0, p: 320, m: "Viguetas, bovedillas, malla", r: "15 m²/día" },
        { n: "Fundición Capa Losa (e=5cm)", u: "m2", c: 1.0, p: 195, m: "Concreto 3k PSI (premezclado)", r: "35 m²/día" },
        { n: "Curado de Concreto", u: "m2", c: 1.0, p: 15, m: "Agua (durante 7 días)", r: "Global" },
        { n: "Red Agua Potable (CPVC)", u: "punto", c: 0.6, p: 480, m: "Tubería, fittings, pegamento", r: "4 ptos/día" },
        { n: "Repello de Muros (Interior)", u: "m2", c: 2.5, p: 85, m: "Mortero 1:3 Cemento-Arena", r: "20 m²/día" },
        { n: "Cernido Fino (Interior)", u: "m2", c: 2.5, p: 65, m: "Mortero 1:5 Cemento-Cal-Arena", r: "22 m²/día" },
        { n: "Repello y Cernido (Exterior)", u: "m2", c: 1.2, p: 160, m: "Mortero 1:3 y 1:5", r: "18 m²/día" },
        { n: "Impermeabilización Losa/Techo", u: "m2", c: 1.0, p: 95, m: "Manta asfáltica o líquido", r: "40 m²/día" },
        { n: "Cielo Falso Drywall/PVC", u: "m2", c: 1.0, p: 145, m: "Perfiles, láminas, tornillos", r: "16 m²/día" },
        { n: "Piso Cerámico (40x40cm)", u: "m2", c: 1.0, p: 165, m: "Cerámica, pegamix, sisa", r: "11 m²/día" },
        { n: "Azulejo en Baños/Cocinas", u: "m2", c: 0.5, p: 185, m: "Azulejo, pegamento, boquilla", r: "7 m²/día" },
        { n: "Ventanería Aluminio (Estándar)", u: "m2", c: 0.3, p: 750, m: "Marco, vidrio 5mm, sellador", r: "4 unid/día" },
        { n: "Puertas Interiores (MDF)", u: "unid", c: 0.08, p: 1250, m: "Puerta, marco, chapa", r: "3 unid/día" },
        { n: "Pintura Látex (2 manos)", u: "m2", c: 4.0, p: 45, m: "Sellador, pintura galón", r: "45 m²/día" },
        { n: "Artefactos Sanitarios (Juego)", u: "juego", c: 0.02, p: 2200, m: "Inodoro, lavamanos, ducha", r: "2 juegos/día" },
        { n: "Instalación Eléctrica Final", u: "punto", c: 0.8, p: 285, m: "Tomas, switches, lámparas", r: "18 ptos/día" },
        { n: "Gabinetes de Cocina (Básico)", u: "ml", c: 0.2, p: 1800, m: "Melamina, herrajes", r: "1 ml/día" },
        { n: "Portón y Herrería Exterior", u: "m2", c: 0.05, p: 850, m: "Metal, pintura anticorrosiva", r: "1 m²/día" },
        { n: "Limpieza Final de Obra", u: "m2", c: 1.0, p: 25, m: "Removedores, limpieza profunda", r: "55 m²/día" },
        // Desde DB externa: añadir exactos faltantes
        { n: "Losa Vigueta/Bovedilla", u: "m2", c: 1.0, p: 320, m: "Viguetas y bovedillas" }
    ],
    comercial: [
        { n: "Movimiento de Tierras Masivo", u: "m3", c: 0.5, p: 85, m: "Excavadora, camiones", r: "100 m³/día" },
        { n: "Compactación Masiva (Rodillo)", u: "m2", c: 1.0, p: 30, m: "Rodillo vibratorio, agua", r: "500 m²/día" },
        { n: "Fundación (Zapatas Aisladas)", u: "unid", c: 0.1, p: 1200, m: "Acero 1/2, Concreto 4k PSI", r: "5 unid/día" },
        { n: "Columnas Estructurales (C2)", u: "unid", c: 0.05, p: 850, m: "Acero 5/8, Concreto 4k PSI", r: "2 unid/día" },
        { n: "Estructura Metálica (Naves)", u: "lb", c: 45, p: 12, m: "Vigas H, soldadura, pernos", r: "2000 lbs/día" },
        { n: "Muro Cortafuego (Block/Panel)", u: "m2", c: 1.5, p: 350, m: "Panel RF o Block con relleno", r: "10 m²/día" },
        { n: "Techo de Lámina Aluzinc (TR-4)", u: "m2", c: 1.0, p: 180, m: "Lámina, estructura metálica L", r: "50 m²/día" },
        { n: "Piso Industrial (Endurecido)", u: "m2", c: 1.0, p: 210, m: "Concreto 3k PSI, endurecedor, fibra", r: "30 m²/día" },
        { n: "Instalación Eléctrica Trifásica", u: "punto", c: 0.2, p: 750, m: "Cable THW, tubería EMT, breakers", r: "5 ptos/día" },
        { n: "Tableros Eléctricos y Subestación", u: "unid", c: 0.01, p: 8500, m: "Tablero, barras, medidor", r: "1 unid/2 días" },
        { n: "Red Hidráulica (Acero Galvanizado)", u: "ml", c: 0.5, p: 250, m: "Tubería HG, válvulas", r: "10 ml/día" },
        { n: "Drenajes PVC (6', 8')", u: "ml", c: 0.8, p: 180, m: "Tubería, pozos de visita", r: "8 ml/día" },
        { n: "Sistema Contra Incendios (Anillos)", u: "ml", c: 0.1, p: 450, m: "Tubería roja, sprinklers, bomba", r: "5 ml/día" },
        { n: "Oficinas Administrativas (Tablaroca)", u: "m2", c: 0.3, p: 180, m: "Tablaroca, perfiles, tornillos", r: "15 m²/día" },
        { n: "Cielo Falso Acústico (2x4)", u: "m2", c: 0.8, p: 120, m: "Perfilería, paneles acústicos", r: "20 m²/día" },
        { n: "Pintura Epóxica de Pisos", u: "m2", c: 1.0, p: 90, m: "Imprimante, pintura epóxica (2 manos)", r: "40 m²/día" },
        { n: "Andenes de Carga (Rampa Concreto)", u: "ml", c: 0.05, p: 2500, m: "Concreto, acero, defensas", r: "0.5 ml/día" },
        { n: "Instalación de Montacargas", u: "unid", c: 0.01, p: 15000, m: "Equipo, adecuación", r: "Global" },
        { n: "Ventilación Industrial (Extractores)", u: "unid", c: 0.05, p: 1800, m: "Extractores eólicos/eléctricos", r: "2 unid/día" },
        { n: "Ventanería Comercial (Vidrio Temp.)", u: "m2", c: 0.2, p: 900, m: "Vidrio templado, aluminio anodizado", r: "2 m²/día" },
        { n: "Puertas de Emergencia (Cortafuego)", u: "unid", c: 0.02, p: 1800, m: "Puerta RF, barra antipánico", r: "1 unid/día" },
        { n: "Señalización Interna/Externa", u: "unid", c: 0.1, p: 350, m: "Señales de seguridad, extintores", r: "10 unid/día" },
        { n: "Cerramiento Perimetral (Muro/Malla)", u: "ml", c: 0.5, p: 220, m: "Block, malla ciclón, concertina", r: "15 ml/día" },
        { n: "Garita de Seguridad", u: "unid", c: 0.01, p: 12000, m: "Block, losa, ventanas, puerta", r: "Global" },
        { n: "Portones Industriales (Corredizos)", u: "unid", c: 0.01, p: 7000, m: "Estructura metálica, motor", r: "1 unid/2 días" },
        { n: "Iluminación Industrial (Led Alta B.)", u: "punto", c: 0.3, p: 450, m: "Luminarias LED, cableado", r: "8 ptos/día" },
        { n: "Sistema de Cámaras (CCTV)", u: "punto", c: 0.1, p: 600, m: "Cámaras, DVR, cableado", r: "5 ptos/día" },
        { n: "Jardinizacion y Áreas Verdes", u: "m2", c: 0.1, p: 40, m: "Tierra negra, plantas, grama", r: "50 m²/día" },
        { n: "Parqueo (Asfalto/Concreto)", u: "m2", c: 0.5, p: 150, m: "Base granular, asfalto/concreto", r: "100 m²/día" },
        { n: "Pintura Exterior (Base Elastomérica)", u: "m2", c: 1.0, p: 70, m: "Pintura industrial, andamios", r: "30 m²/día" },
        { n: "Limpieza Final de Naves", u: "m2", c: 1.0, p: 30, m: "Limpieza profunda de estructuras", r: "100 m²/día" },
        { n: "Pruebas y Puestas en Marcha", u: "global", c: 1.0, p: 5000, m: "Pruebas, comisionado", r: "Global" }
    ],
    // Industrial - añadidos exactos desde bloque externo
    industrial: [
        { n: "Estructura Metálica H", u: "ton", c: 0.005, p: 2500, m: "Acero A36" },
        { n: "Piso Epóxico ESD", u: "m2", c: 1.0, p: 250, m: "Resina conductiva" },
        { n: "Extractores Eólicos", u: "unid", c: 0.02, p: 1800, m: "Extractores eólicos" },
        { n: "Instalación Aire Comprimido", u: "ml", c: 0.5, p: 180, m: "Tubería galvanizada" },
        { n: "Cimentación de Maquinaria Pesada", u: "m3", c: 0.05, p: 1800, m: "Concreto 5k PSI, anclajes", r: "1 m³/día" },
        { n: "Losa Postensada", u: "m2", c: 0.01, p: 600, m: "Concreto, torones, anclajes", r: "5 m²/día" },
        { n: "Estructura para Grúas Puente", u: "ton", c: 0.005, p: 2500, m: "Acero estructural A36, soldadura", r: "0.1 ton/día" },
        { n: "Cubierta Tipo Sandwich Panel", u: "m2", c: 1.0, p: 280, m: "Panel aislante, remates", r: "30 m²/día" },
        { n: "Sistemas de Evacuación de Humos", u: "unid", c: 0.01, p: 4500, m: "Campanas, ductos, extractores", r: "Global" },
        { n: "Instalaciones de Aire Comprimido", u: "ml", c: 0.5, p: 180, m: "Tubería galvanizada, compresor", r: "10 ml/día" },
        { n: "Red de Tierras Industriales", u: "punto", c: 0.05, p: 800, m: "Electrodos, cableado, puestas a tierra", r: "2 ptos/día" },
        { n: "Protección Catódica", u: "ml", c: 0.01, p: 1200, m: "Ánodos de sacrificio, cableado", r: "Global" },
        { n: "Tanques de Almacenamiento (Concreto)", u: "m3", c: 0.001, p: 5000, m: "Concreto armado, recubrimiento epóxico", r: "Global" },
        { n: "Tratamiento de Aguas Residuales Industriales", u: "m3/día", c: 0.001, p: 25000, m: "Filtros, bombas, químicos", r: "Global" },
        { n: "Cercado de Seguridad con Sensores", u: "ml", c: 0.05, p: 350, m: "Malla, sensores infrarrojos, concertina", r: "8 ml/día" },
        { n: "Puertas Rápidas Industriales", u: "unid", c: 0.01, p: 6000, m: "Puerta enrollable, motor", r: "Global" },
        { n: "Aislamiento Acústico de Áreas", u: "m2", c: 0.05, p: 400, m: "Paneles aislantes, barreras de sonido", r: "10 m²/día" },
        { n: "Piso Antiestático ESD", u: "m2", c: 0.01, p: 250, m: "Recubrimiento epóxico conductivo", r: "20 m²/día" },
        { n: "Sistema de Gestión de Edificios (BMS)", u: "punto", c: 0.001, p: 15000, m: "Controladores, sensores, integracion", r: "Global" },
        { n: "Protecciones y Barandas Industriales", u: "ml", c: 0.1, p: 95, m: "Barandas de acero, pinturas", r: "25 ml/día" },
        { n: "Sistemas de Ventilación Forzada", u: "unid", c: 0.02, p: 2200, m: "Ventiladores, conductos", r: "5 unid/día" },
        { n: "Control de Vibraciones", u: "punto", c: 0.005, p: 1200, m: "Aisladores, bases", r: "Global" },
        { n: "Sistemas de Filtración (Polvo)", u: "unid", c: 0.01, p: 3200, m: "Filtros, ventiladores, ductos", r: "Global" },
        { n: "Red de Drenaje Industrial", u: "ml", c: 0.2, p: 220, m: "Tubería, sumideros, rejillas", r: "12 ml/día" },
        { n: "Saneamiento y Alcantarillado", u: "ml", c: 0.2, p: 180, m: "Tubería, pozos, conexiones", r: "15 ml/día" },
        { n: "Instalación de Bancadas y Bases", u: "unid", c: 0.02, p: 800, m: "Hormigón, anclajes", r: "5 unid/día" },
        { n: "Pasarelas y Accesos Metálicos", u: "m2", c: 0.1, p: 450, m: "Perfil metálico, rejilla antideslizante", r: "20 m²/día" },
        { n: "Sistemas de Seguridad Industrial (PLC)", u: "punto", c: 0.005, p: 6000, m: "PLC, sensores, actuadores", r: "Global" },
        { n: "Pavimentos Especiales (Carga Pesada)", u: "m2", c: 0.5, p: 420, m: "Concreto reforzado, malla", r: "25 m²/día" },
        { n: "Estaciones de Carga Eléctrica", u: "unid", c: 0.02, p: 2200, m: "Punto de carga, cableado", r: "3 unid/día" },
        { n: "Cubiertas con Aislamiento Térmico", u: "m2", c: 1.0, p: 340, m: "Aislamiento, membrana impermeable", r: "30 m²/día" },
        { n: "Red de Control Ambiental (HVAC)", u: "punto", c: 0.02, p: 4500, m: "Unidades HVAC, conductos", r: "Global" },
        { n: "Sistemas de Prevención de Corrosión", u: "m2", c: 0.2, p: 95, m: "Recubrimientos, tratamiento superficial", r: "50 m²/día" },
        { n: "Señalización y Marcaje de Seguridad", u: "unid", c: 0.1, p: 120, m: "Marcadores, pinturas reflectantes", r: "50 unid/día" },
        { n: "Limpieza Final Industrial", u: "m2", c: 1.0, p: 35, m: "Limpieza especializada", r: "200 m²/día" },
        { n: "Pruebas y Puestas en Marcha", u: "global", c: 1.0, p: 5000, m: "Pruebas, comisionado", r: "Global" }
    ],
    civil: [
        { n: "Excavación para Tubería", u: "m3", c: 0.25, p: 95, m: "Zanja para red hidráulica" },
        { n: "Capa de Base Granular", u: "m3", c: 0.15, p: 220, m: "Material clasificado compactado" },
        { n: "Pavimento Hidráulico t=15cm", u: "m2", c: 1.0, p: 285, m: "Concreto 4000 PSI reforzado" },
        { n: "Bordillo Tipo A", u: "ml", c: 0.2, p: 135, m: "Fundido en sitio" },
        { n: "Movimientos de Tierra (Excavación)", u: "m3", c: 0.5, p: 60, m: "Maquinaria, camiones", r: "500 m³/día" },
        { n: "Sub-Base Granular", u: "m2", c: 0.5, p: 45, m: "Material granular, compactacion", r: "300 m²/día" },
        { n: "Base de Concreto Hidráulico", u: "m3", c: 0.02, p: 420, m: "Concreto, vibrado", r: "20 m³/día" },
        { n: "Estructuras de Drenaje (Aletas)", u: "ml", c: 0.4, p: 160, m: "Tubería, cámaras", r: "30 ml/día" },
        { n: "Muros de Contención (Hormigón)", u: "m3", c: 0.02, p: 850, m: "Hormigón, encofrado, acero", r: "10 m³/día" },
        { n: "Puentes Peatonales (Losas)", u: "m2", c: 0.01, p: 950, m: "Losas, armaduras", r: "10 m²/día" },
        { n: "Cunetas y Alcantarillas", u: "ml", c: 0.6, p: 85, m: "Tubería, concreto prefabricado", r: "80 ml/día" },
        { n: "Pavimento Asfáltico (Capas)", u: "m2", c: 0.8, p: 120, m: "Asfalto, rodillo", r: "200 m²/día" },
        { n: "Señalización Vial Horizontal", u: "m2", c: 0.02, p: 35, m: "Pintura termoplástica", r: "500 m²/día" },
        { n: "Iluminación Vial", u: "unid", c: 0.02, p: 1450, m: "Postes, luminarias LED", r: "5 unid/día" },
        { n: "Paso a Nivel / Accesos", u: "ml", c: 0.05, p: 320, m: "Base, pavimento", r: "20 ml/día" },
        { n: "Red de Agua Potable (Mayor)", u: "ml", c: 0.6, p: 300, m: "Tubería DI/HDPE", r: "60 ml/día" },
        { n: "Estaciones de Bombeo", u: "unid", c: 0.01, p: 12000, m: "Bomba, tuberia", r: "Global" },
        { n: "Estabilizacion de Taludes", u: "m2", c: 0.2, p: 180, m: "Geomalla, anclajes", r: "50 m²/día" },
        { n: "Tendidos de Pavimento Rigido (Losas)", u: "m2", c: 0.5, p: 260, m: "Concreto, juntas", r: "80 m²/día" },
        { n: "Señales Verticales y Semáforos", u: "unid", c: 0.02, p: 750, m: "Estructura, luminaria", r: "5 unid/día" },
        { n: "Muros de Gabion", u: "m3", c: 0.02, p: 220, m: "Gabion, piedra", r: "15 m³/día" },
        { n: "Obras de Arte (Acueductos)", u: "unid", c: 0.01, p: 18000, m: "Estructura, bomba", r: "Global" },
        { n: "Rehabilitación Estructural", u: "m2", c: 0.2, p: 320, m: "Refuerzo, epoxis", r: "30 m²/día" },
        { n: "Protectores de Talud Vegetal", u: "m2", c: 0.1, p: 45, m: "Malla, vegetacion", r: "100 m²/día" },
        { n: "Redes Pluviales (Alcantarillado)", u: "ml", c: 0.6, p: 160, m: "Tubería, sumideros", r: "60 ml/día" },
        { n: "Control Geotecnico y Ensayos", u: "global", c: 1.0, p: 2500, m: "Ensayos, laboratorio", r: "Global" },
        { n: "Sistemas de Riego y Parques", u: "m2", c: 0.05, p: 55, m: "Tubos, aspersores", r: "200 m²/día" },
        { n: "Cimentaciones Especiales (Pilotes)", u: "ml", c: 0.02, p: 950, m: "Pilotes, perforacion", r: "5 ml/día" },
        { n: "Pasos Peatonales y Accesos", u: "m2", c: 0.5, p: 120, m: "Concreto, acabados", r: "150 m²/día" },
        { n: "Mobiliario Urbano (Bancos/Lumin.)", u: "unid", c: 0.02, p: 450, m: "Fabricacion, instalacion", r: "20 unid/día" },
        { n: "Señalización y Seguridad Vial", u: "unid", c: 0.05, p: 150, m: "Señales, defensas", r: "50 unid/día" },
        { n: "Obras de Cruce y Pasos Inferiores", u: "unid", c: 0.005, p: 45000, m: "Estructura, excavacion", r: "Global" },
        { n: "Revestimiento y Protección de Riberas", u: "m2", c: 0.1, p: 220, m: "Geotextil, roca", r: "75 m²/día" },
        { n: "Limpieza y Señalizacion Final", u: "m2", c: 1.0, p: 25, m: "Limpieza, señalizacion", r: "500 m²/día" }
    ],
    // Civil - añadidos exactos desde bloque externo
    civil: [
        { n: "Cunetas de Concreto", u: "ml", c: 0.2, p: 210, m: "Concreto 3k PSI" },
        { n: "Bordillos Prefabricados", u: "ml", c: 0.2, p: 145, m: "Concreto de alta resistencia" },
        { n: "Pozos de Visita", u: "unid", c: 0.01, p: 4500, m: "Ladrillo y tapadera fundición" },
        { n: "Asfalto en Caliente (10cm)", u: "m2", c: 1.0, p: 195, m: "Mezcla asfáltica" },
        { n: "Vivienda Social Tipo A", u: "m2", c: 1.0, p: 650, m: "Estructura, acabados básicos", r: "20 m²/día" },
        { n: "Centro Comunitario (Pequeño)", u: "m2", c: 1.0, p: 820, m: "Estructura mixto, acabados", r: "25 m²/día" },
        { n: "Aulas Escolares (Modulo)", u: "m2", c: 1.0, p: 780, m: "Estructura, acabados, ventilacion", r: "30 m²/día" },
        { n: "Sede de Salud (Puesto)", u: "m2", c: 1.0, p: 900, m: "Acabados, instalaciones medicas basicas", r: "20 m²/día" },
        { n: "Red de Agua Potable Comunitaria", u: "ml", c: 0.6, p: 220, m: "Tuberia, tanques", r: "40 ml/día" },
        { n: "Red de Alumbrado Público", u: "unid", c: 0.02, p: 1200, m: "Poste, luminaria LED", r: "10 unid/día" },
        { n: "Adoquinado y Pavimento", u: "m2", c: 0.8, p: 140, m: "Base, adoquines", r: "120 m²/día" },
        { n: "Parques Infantiles (Equipamiento)", u: "unid", c: 0.02, p: 4500, m: "Juegos, piso de seguridad", r: "Global" },
        { n: "Bordillos y Aceras", u: "ml", c: 0.5, p: 65, m: "Concreto, acabados", r: "150 ml/día" },
        { n: "Puestos de Salud y Atención", u: "unid", c: 0.01, p: 28000, m: "Estructura, instalaciones", r: "Global" },
        { n: "Edificios Administrativos Locales", u: "m2", c: 1.0, p: 950, m: "Estructura, acabados", r: "25 m²/día" },
        { n: "Centros Deportivos (Basico)", u: "m2", c: 1.0, p: 700, m: "Grama sintetica, pistas", r: "50 m²/día" },
        { n: "Mejoramiento de Plazas y Parques", u: "m2", c: 0.5, p: 120, m: "Pavimentos, jardineria", r: "200 m²/día" },
        { n: "Obras de Protección Social (Refugios)", u: "m2", c: 1.0, p: 620, m: "Estructura basica, cubiertas", r: "20 m²/día" },
        { n: "Redes de Desagüe Pluvial", u: "ml", c: 0.6, p: 140, m: "Tuberia, rejillas", r: "80 ml/día" },
        { n: "Mejoramiento de Centros Culturales", u: "m2", c: 1.0, p: 780, m: "Acabados, iluminacion", r: "30 m²/día" },
        { n: "Centros Tecnológicos (Modulo)", u: "m2", c: 1.0, p: 1100, m: "Instalaciones, redes", r: "25 m²/día" },
        { n: "Estaciones de Bus (Pequeñas)", u: "unid", c: 0.02, p: 4200, m: "Estructura, cubierta", r: "Global" },
        { n: "Mejoramiento de Mercados Locales", u: "m2", c: 1.0, p: 820, m: "Estructura, acabados comerciales", r: "40 m²/día" },
        { n: "Mantenimiento de Infraestructura Vial", u: "m2", c: 1.0, p: 95, m: "Reparacion y bacheo", r: "300 m²/día" },
        { n: "Accesibilidad y Rampas", u: "ml", c: 0.2, p: 110, m: "Concreto, barandas", r: "100 ml/día" },
        { n: "Canchas Deportivas (Mejora)", u: "m2", c: 1.0, p: 420, m: "Superficie, marquesinas", r: "80 m²/día" },
        { n: "Señalización y Seguridad Publica", u: "unid", c: 0.1, p: 220, m: "Señales, postes", r: "80 unid/día" },
        { n: "Instalaciones Sanitarias Comunitarias", u: "unid", c: 0.02, p: 3200, m: "Construccion, equipos sanitarios", r: "Global" },
        { n: "Estabilizacion de Suelos y Terraplenes", u: "m2", c: 0.2, p: 160, m: "Geotextiles, compaction", r: "100 m²/día" },
        { n: "Paisajismo y Mejoras Verdes", u: "m2", c: 0.1, p: 65, m: "Plantas, riego", r: "200 m²/día" },
        { n: "Iluminación Escénica y Monumentos", u: "unid", c: 0.02, p: 950, m: "Luminarias, montaje", r: "10 unid/día" },
        { n: "Módulos de Seguridad Pública", u: "unid", c: 0.01, p: 14000, m: "Estructura, comunicaciones", r: "Global" },
        { n: "Limpieza y Entrega de Obra Pública", u: "m2", c: 1.0, p: 30, m: "Limpieza, señalizacion final", r: "500 m²/día" }
    ]
};

// Precios de mercado editables para SOFTCON-WM (valores por defecto)
let PRECIOS_MAESTROS = {
    cemento: 85.00,  // Precio por saco
    hierro: 385.00,  // Precio por quintal
    arena: 150.00,   // Precio por m3
    piedrin: 175.00, // Precio por m3
    block: 4.50      // Precio por unidad
};

// Pública - añadidos exactos desde bloque externo
baseDatos.publica.push({ n: "Mobiliario Urbano (Bancas)", u: "unid", c: 0.01, p: 3200, m: "Hierro y madera tratada" });
baseDatos.publica.push({ n: "Postes Alumbrado Solar", u: "unid", c: 0.005, p: 8500, m: "Panel 100W, Batería Litio" });
baseDatos.publica.push({ n: "Señalización Vial", u: "km", c: 0.001, p: 12000, m: "Pintura termoplástica" });

// Puedes ampliar o ajustar los renglones directamente en este archivo `datos.js`.

